apiVersion: apps/v1
kind: Deployment
metadata:
  name: markdown-editor
  labels:
    app: markdown-editor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: markdown-editor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: markdown-editor
    spec:
      containers:
      - name: markdown-editor
        image: ${DOCKER_REGISTRY:-localhost}/markdown-editor:${IMAGE_TAG:-latest}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2 